# Generated by Django 4.0.4 on 2022-07-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edudetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education', models.CharField(max_length=70)),
                ('College', models.CharField(max_length=150)),
                ('Year_of_Passing', models.IntegerField()),
                ('University', models.CharField(max_length=200)),
                ('Marks', models.FloatField()),
            ],
        ),
    ]
